Update packages + use @cityssm/unleeter to unleet
Bobrobot1/Suicide-Prevention-Bot pull request #28
Opened 2022-01-16 09:59 UTC by CPlusPatch

Updated ansi and string-width packages to fix minor security issues and added @cityssm/unleeter to unleet messages for better keyword detection (so that it is harder for people to mask their messages with leetcode)

2022-01-16 15:06 UTC, CatusKing requested changes

2022-01-16 15:06 UTC, CatusKing commented on .vscode/settings.json
> +{
why did you commit this

2022-01-16 15:07 UTC, CPlusPatch commented on .vscode/settings.json
> +{
Whoops sorry forgot about that

2022-01-16 15:10 UTC, CPlusPatch commented on .vscode/settings.json
> +{
I made a fix, will commit it now

2022-01-18 13:20 UTC, CatusKing approved these changes

2022-01-18 13:23 UTC, merged