Multiple major changes
Bobrobot1/Suicide-Prevention-Bot pull request #32
Opened 2022-02-10 21:17 UTC by bubby932

- Moved all commands into separate files.
- Moved processing of triggers and insults into separate files.
- Moved Mention message into separate file.
- Added a (wip) cooldown to sp!dm.
- Minor change to README.md due to security scanning guidelines.
- Fixed missing semicolons.
- Updated command handling to use a switch statement instead of an if/else chain.
- Added a configuration value to change how often the status updates, default 15.
- Updated code comments and added spaces where necessary.
- Added line breaks between multiple code blocks for readability.
- Added #region blocks for ease of reading.

2022-02-11 02:44 UTC, CatusKing requested changes

2022-02-11 02:44 UTC, CatusKing commented on index.js
> +  switch(command) {
bad ise a for loop on a n object of commands

2022-02-11 02:44 UTC, CatusKing commented on index.js
> +    return require('./commands/ping')(message, lang);
stop reading the files upon every call upon the command files
use a basic command handler

2022-02-11 02:51 UTC, bubby932 commented
@CatusKing I'll resolve those tomorrow, however for the switch statement i was intentionally using it to cut down on the need for loops, are you sure you want me to change that?

2022-02-11 02:53 UTC, bubby932 commented
also the files are cached on the first read, they are not re read every time require() is called. 
![image](https://user-images.githubusercontent.com/82341739/153530602-307c0ab7-8aea-4401-9ad2-f3cbf96920bf.png)

2022-02-11 02:59 UTC, CatusKing commented
> also the files are cached on the first read, they are not re read every time require() is called. ![image](https://user-images.githubusercontent.com/82341739/153530602-307c0ab7-8aea-4401-9ad2-f3cbf96920bf.png)

hmmm interesting didn't know but for me i've been taught its better practice to use an object with a simple for loop or the Collection offers a .get(key)

2022-02-11 03:01 UTC, bubby932 commented
> > also the files are cached on the first read, they are not re read every time require() is called. ![image](https://user-images.githubusercontent.com/82341739/153530602-307c0ab7-8aea-4401-9ad2-f3cbf96920bf.png)
> 
> hmmm interesting didn't know but for me i've been taught its better practice to use an object with a simple for loop or the Collection offers a .get(key)

alright

2022-02-19 04:37 UTC, Killerjet101 commented
Those are older reviews as they've all been fixed in the canary branch

2022-02-19 10:54 UTC, CPlusPatch commented
So we can close this, since it's already been merged in canary

2022-02-20 09:14 UTC, closed without merging